{
  "formatVersion": "1.1",
  "component": {
    "group": "AndroidX_Jetpack",
    "module": "router-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-unspecified.jar",
          "url": "router-plugin-unspecified.jar",
          "size": 26279,
          "sha512": "cfa3dcf55f2b00d1bf859b5e2a52f9f24ebcc0c014c3b2e95da35aca422be0b8dcb16645e73b9eaf5d045a1cfc333122fed8cc2f0ffaaef717bcd3cf4b408156",
          "sha256": "913265c643831e75101ea5aa674e06f75bf181892e234b1635a898a7b9cffc30",
          "sha1": "031bc10a7899a618dbb8345e31fc7ef346cfab80",
          "md5": "47aa4782a9fe45080bcd5edd53c9919c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-unspecified.jar",
          "url": "router-plugin-unspecified.jar",
          "size": 26279,
          "sha512": "cfa3dcf55f2b00d1bf859b5e2a52f9f24ebcc0c014c3b2e95da35aca422be0b8dcb16645e73b9eaf5d045a1cfc333122fed8cc2f0ffaaef717bcd3cf4b408156",
          "sha256": "913265c643831e75101ea5aa674e06f75bf181892e234b1635a898a7b9cffc30",
          "sha1": "031bc10a7899a618dbb8345e31fc7ef346cfab80",
          "md5": "47aa4782a9fe45080bcd5edd53c9919c"
        }
      ]
    }
  ]
}
