{
  "formatVersion": "1.1",
  "component": {
    "group": "AndroidX_Jetpack",
    "module": "router-plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-unspecified.jar",
          "url": "router-plugin-unspecified.jar",
          "size": 26276,
          "sha512": "89730030f4ff54bb7ea91d5d9981771ff767b5dcf93b7cf8d143a2499f5b7b7f1d53932ddac65d76e49e175fd649e72e887857fcf893f6128e5823898eed1e01",
          "sha256": "7a992bf86721ca18c545f28ece52b4b0bf7f181dd8736266f7eed89f33fb454e",
          "sha1": "b9ce580b851c756e13e120a1c9826fdea5a5c695",
          "md5": "842fd57f21b868d4caf81dac06214ebc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-unspecified.jar",
          "url": "router-plugin-unspecified.jar",
          "size": 26276,
          "sha512": "89730030f4ff54bb7ea91d5d9981771ff767b5dcf93b7cf8d143a2499f5b7b7f1d53932ddac65d76e49e175fd649e72e887857fcf893f6128e5823898eed1e01",
          "sha256": "7a992bf86721ca18c545f28ece52b4b0bf7f181dd8736266f7eed89f33fb454e",
          "sha1": "b9ce580b851c756e13e120a1c9826fdea5a5c695",
          "md5": "842fd57f21b868d4caf81dac06214ebc"
        }
      ]
    }
  ]
}
