{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "router-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 47995,
          "sha512": "97f921f733954256da73992a310b8fe3ef47502914107057dbae2aa456460d8224034bbe5259dd5b0e18c19cbd55b64611c941619cbec356d69c251e6867fc2a",
          "sha256": "10d41b07cb27ff6f48df7bf31464213a0d652c27822db1c3d3e5bada77c33d94",
          "sha1": "41ebc97af6ca53a9d6285a6ab96e5a14309b9add",
          "md5": "50dd8ba476fba5a212b4e2f97b36614c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 47995,
          "sha512": "97f921f733954256da73992a310b8fe3ef47502914107057dbae2aa456460d8224034bbe5259dd5b0e18c19cbd55b64611c941619cbec356d69c251e6867fc2a",
          "sha256": "10d41b07cb27ff6f48df7bf31464213a0d652c27822db1c3d3e5bada77c33d94",
          "sha1": "41ebc97af6ca53a9d6285a6ab96e5a14309b9add",
          "md5": "50dd8ba476fba5a212b4e2f97b36614c"
        }
      ]
    }
  ]
}
