{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "router-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 50662,
          "sha512": "341610d349e72bf4bfc0ecad841ca4529a237137364ac83087472fa7df390acd17827a5967d61d9e52d6fdfa62aedffb2cffb4745446a379dcd3eb4d3dfd0895",
          "sha256": "d99bc46e9535fde7056b27c98df705d9c90a3694f0072be129c60f41958ad50b",
          "sha1": "70527e46024b04ee94e26c8bd390fb75b49c1457",
          "md5": "30beba368a86b7eb1169b96248e0cd97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "router-plugin-1.0.0.jar",
          "url": "router-plugin-1.0.0.jar",
          "size": 50662,
          "sha512": "341610d349e72bf4bfc0ecad841ca4529a237137364ac83087472fa7df390acd17827a5967d61d9e52d6fdfa62aedffb2cffb4745446a379dcd3eb4d3dfd0895",
          "sha256": "d99bc46e9535fde7056b27c98df705d9c90a3694f0072be129c60f41958ad50b",
          "sha1": "70527e46024b04ee94e26c8bd390fb75b49c1457",
          "md5": "30beba368a86b7eb1169b96248e0cd97"
        }
      ]
    }
  ]
}
